### ISSUE TITLE
Random BoundsError()

### ISSUE THREAD

**Issue by yhalk** [KristofferC/KDTrees.jl#15] opened 2015-09-01 07:19 UTC
Hello,

I am trying to create some KDTrees for 117-dimensional data, yet the success of building the tree seems to be a bit random, e.g I can create a tree with 200000 points, but when I move on to create one with just 70000, I get the following error:

ERROR: BoundsError()
 in build_KDTree at /home/ichalkia/.julia/v0.3/KDTrees/src/kd_tree.jl:277
 in KDTree at /home/ichalkia/.julia/v0.3/KDTrees/src/kd_tree.jl:168
 in anonymous at no file:82
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128

Or, I might manage to create a few trees (with dimensions and data same as above) before I run into this error. 
However, I have used the package successfully before and I have not changed anything in my code since then.

Does anyone have any ideas why this is happening and how to deal with it?

Thanks in advance!

**Comment by KristofferC** [comment] 2015-09-01 07:33
That's odd, I haven't changed the code to the tree builder in a long time and I don't think I have ever gotten a BoundsError in the builder. How frequent are the errors? Is it with some special type of data?

I tried

``` julia
for i = 1:100
    tree = KDTree(rand(117, 70000))
end
```

and it ran fine.

If you are using random data, is it possible for you to try to set the seed of the PRNG with `srand(xxx)` where `xxx` is a number that makes the following call to `KDTree` fail. In that way we can make sure that we are calling the builder with the exact same data.

**Comment by yhalk** [comment] 2015-09-01 08:03
Thanks for the quick reply!

I am using speech data (MFCCs) and I get errors every time I try to create a tree; building the tree is actually the exception.
With random data, it works fine for me as well.

**Comment by KristofferC** [comment] 2015-09-01 08:16
Is there any way you could give me something concrete I can run? Can you create a smaller data file that also triggers the error? Is it only with dimension 117, is it only with 70000 points? Just dump all info you have hehe.

I guess there is some special feature with your data that triggers a boundary case that doesn't show up when testing with random data. The way I create the tree is

**Comment by yhalk** [comment] 2015-09-01 08:39
Unfortunately ,  I cannot share the data; they are proprietary.

I can see though that  most of the points are the same (could be a pre-processing issue). Could  that be the failure reason?

**Comment by KristofferC** [comment] 2015-09-01 08:44
Yeah, I was thinking it might be something like that.

This reproduces it:

``` julia
julia> KDTree(ones(1, 11))
ERROR: BoundsError: attempt to access 1x11 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
  at index [-1,6]
 in build_KDTree at /home/kristoffer/.julia/v0.4/KDTrees/src/kd_tree.jl:277
 in KDTree at /home/kristoffer/.julia/v0.4/KDTrees/src/kd_tree.jl:168
```

I will look into it.

**Comment by KristofferC** [comment] 2015-09-01 09:04
Could you try the new commit and see if things works? Just do a `Pkg.checkout("KDTrees")` and julia should update to the newest master branch.

**Comment by KristofferC** [comment] 2015-09-01 09:34
By the way, for such high dimensional data, is a kd tree really that good? A ball tree is likely to blow it out of the water.

**Comment by yhalk** [comment] 2015-09-02 20:51
Tried the new commit, but I'm still getting the same error.

Thanks for the suggestion for ball trees. So far I haven't been able to find a Julia implementation though.

**Comment by KristofferC** [comment] 2015-09-02 22:26
Strange, that bug I found sounded like it was exactly your problem. You are sure you are on the newest commit?

I wrote some code half a year ago that was meant to provide a more complete NearestNeighbour package but due to time constraint I had to discontinue working on it. Haven't had time to pick it up again.

It does include a ball tree and it should be working though so I uploaded it.

Can you try the "trythis" branch at https://github.com/KristofferC/NearestNeighbour.jl/tree/trythis

The API is a bit different since I wanted to incorporate different metrics, here is an example:

``` julia
julia> using NearestNeighbour

julia> balltree = BallTree(rand(117,70000))
NearestNeighbour.BallTree{Float64} from 70000 point in 117 dimensions.

julia> knn(balltree, rand(117), 5, Euclidian())
([26862,56417,3560,48788,16379],[3.4568297760840427,3.4252994038852473,3.4488478100043176,3.418908887631104,3.3244800794745024])
```

It might be slower than the KDTree because I haven't incorporated the latest optimizations into it but can you try it and see if you get the same error? I don't remember if there might be some bugs in it so you should check if you get same results as with this package.

**Comment by KristofferC** [comment] 2015-09-14 09:30
I will close this now as non reproduceble since I don't have any code to run to trigger the problem. If you could produce some data set that triggers the bug I could likely fix it but by the information I have I can't do anything.

Fee, free to post again with a reproducble piece of code and I will reopen.

**Closed as completed by KristofferC** 2015-09-14 09:30 UTC
Labels: bug
